const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();
async function main() {
  await prisma.jobListing.createMany({
    data: [
      {
        id: "cm00s3ou6000cfasazqit2mex",
        title: "Junior Developer",
        slug: "systems-corp-global-junior-developer",
        description: "",
        company: "Systems Corp Global",
        location: "Worldwide",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "Vue", "JavaScript", "Sass"],
        imgUrl: "",
        createdAt: "2024-08-19T09:13:31.519Z",
      },
      {
        id: "clzx3f1rc00006x7582c3j35p",
        title: "Senior Frontend Developer",
        slug: "photosnap-senior-frontend-developer",
        description: "",
        company: "Photosnap",
        location: "USA",
        permanency: "FULL_TIME",
        featured: true,
        tags: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-16T19:19:12.552Z",
      },
      {
        id: "clzx3j1ui00026x75992x415r",
        title: "Junior Frontend Developer",
        slug: "account-junior-frontend-developer",
        description: "",
        company: "Account",
        location: "USA",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "React", "Sass", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-16T19:22:19.290Z",
      },
      {
        id: "clzx3gpqy00016x75p8k22dwn",
        title: "Fullstack Developer",
        slug: "manage-fullstack-developer",
        description: "",
        company: "Manage",
        location: "Remote",
        permanency: "PART_TIME",
        featured: true,
        tags: ["Fullstack", "Midweight", "Python", "React"],
        imgUrl: "",
        createdAt: "2024-08-16T19:20:30.298Z",
      },
      {
        id: "clzx3mmiv00036x752s3vzj9j",
        title: "Junior Frontend Developer",
        slug: "myhome-junior-frontend-developer",
        description: "",
        company: "MyHome",
        location: "USA",
        permanency: "CONTRACT",
        featured: false,
        tags: ["Frontend", "Junior", "CSS", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-16T19:25:06.055Z",
      },
      {
        id: "clzx3mmiv00046x75yavkc745",
        title: "Software Engineer",
        slug: "loop-studios-software-engineer",
        description: "",
        company: "Loop Studios",
        location: "Worldwide",
        permanency: "FULL_TIME",
        featured: false,
        tags: ["Fullstack", "Midweight", "JavaScript", "Sass", "Ruby"],
        imgUrl: "",
        createdAt: "2024-08-16T19:25:06.055Z",
      },
      {
        id: "clzx3oidc00056x75pytvaass",
        title: "Junior Backend Developer",
        slug: "face-it-junior-backend-developer",
        description: "",
        company: "FaceIt",
        location: "UK",
        permanency: "FULL_TIME",
        featured: false,
        tags: ["Backend", "Junior", "Ruby", "RoR"],
        imgUrl: "",
        createdAt: "2024-08-16T19:26:33.984Z",
      },
      {
        id: "clzx3pxxo00066x75inr23glm",
        title: "Junior Developer",
        slug: "shortly-junior-developer",
        description: "",
        company: "Shortly",
        location: "Worldwide",
        permanency: "FULL_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "HTML", "Sass", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-16T19:27:40.812Z",
      },
      {
        id: "clzx3rsr200076x759yzvqhy9",
        title: "Junior Frontend Developer",
        slug: "insure-junior-frontend-developer",
        description: "",
        company: "Insure",
        location: "USA",
        permanency: "FULL_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "Vue", "JavaScript", "Sass"],
        imgUrl: "",
        createdAt: "2024-08-16T19:29:07.407Z",
      },
      {
        id: "clzx3tbms00086x753dvir07l",
        title: "Full Stack Engineer",
        slug: "eyecam-co-full-stack-engineer",
        description: "",
        company: "Eyecam Co.",
        location: "Worldwide",
        permanency: "FULL_TIME",
        featured: false,
        tags: ["Fullstack", "Midweight", "JavaScript", "Django", "Python"],
        imgUrl: "",
        createdAt: "2024-08-16T19:30:18.533Z",
      },
      {
        id: "clzx3uu0z00096x753x5spsv0",
        title: "Front-end Dev",
        slug: "the-air-filter-company-front-end-dev",
        description: "",
        company: "The Air Filter Company",
        location: "Worldwide",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "React", "Sass", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-16T19:31:29.028Z",
      },
      {
        id: "cm00rj2jc0000fasacqnsto4a",
        title: "Junior Frontend Developer",
        slug: "tech-corp-junior-frontend-developer",
        description: "",
        company: "Tech Corp",
        location: "Worldwide",
        permanency: "FULL_TIME",
        featured: false,
        tags: ["Fullstack", "Midweight", "JavaScript", "Sass", "Ruby", ""],
        imgUrl: "",
        createdAt: "2024-08-19T08:57:29.496Z",
      },
      {
        id: "cm00rkm8t0001fasalev4xsjm",
        title: "Junior Frontend Developer",
        slug: "tech-global-enterprises-junior-frontend-developer",
        description: "",
        company: "Tech Global Enterprises",
        location: "USA",
        permanency: "FULL_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "CSS", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-19T08:58:41.693Z",
      },
      {
        id: "cm00rmeu40002fasalxf9jwtr",
        title: "Junior Developer",
        slug: "consulting-corp-junior-developer",
        description: "",
        company: "Consulting Corp",
        location: "Worldwide",
        permanency: "PART_TIME",
        featured: true,
        tags: ["Fullstack", "Midweight", "Python", "React"],
        imgUrl: "",
        createdAt: "2024-08-19T09:00:05.405Z",
      },
      {
        id: "cm00rpckr0004fasa0tcwni5v",
        title: "Software Engineer",
        slug: "innovations-networks-software-engineer",
        description: "",
        company: "Innovations Networks",
        location: "Worldwide",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Backend", "Junior", "Ruby", "RoR"],
        imgUrl: "",
        createdAt: "2024-08-19T09:02:22.444Z",
      },
      {
        id: "cm00rnydi0003fasar8hu25bh",
        title: "Front-end Dev",
        slug: "dynamics-technologies-dynamics-front-end-dev",
        description: "",
        company: "Dynamics Technologies Dynamics",
        location: "Worldwide",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "React", "Sass", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-19T09:01:17.383Z",
      },
      {
        id: "cm00rrluw0005fasai7esrsqy",
        title: "Full Stack Engineer",
        slug: "enterprises-full-stack-engineer",
        description: "",
        company: "Enterprises",
        location: "USA",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-19T09:04:07.785Z",
      },
      {
        id: "cm00rtcyi0006fasal0ub888p",
        title: "Fullstack Developer",
        slug: "industries-fullstack-developer",
        description: "",
        company: "Industries",
        location: "UK",
        permanency: "FULL_TIME",
        featured: false,
        tags: ["Backend", "Junior", "Ruby", "RoR"],
        imgUrl: "",
        createdAt: "2024-08-19T09:05:29.562Z",
      },
      {
        id: "cm00rv20x0007fasaz4f23xj8",
        title: "Junior Frontend Developer",
        slug: "technologies-corp-dynamics-junior-frontend-developer",
        description: "",
        company: "Technologies Corp Dynamics",
        location: "USA",
        permanency: "FULL_TIME",
        featured: true,
        tags: ["Frontend", "Junior", "React", "Sass", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-19T09:06:48.705Z",
      },
      {
        id: "cm00rwiu60008fasa5fc3eb42",
        title: "Junior Developer",
        slug: "innovations-dynamics-corp-junior-developer",
        description: "",
        company: "Innovations Dynamics Corp",
        location: "USA",
        permanency: "CONTRACT",
        featured: false,
        tags: ["Fullstack", "Midweight", "Python", "React"],
        imgUrl: "",
        createdAt: "2024-08-19T09:07:57.150Z",
      },
      {
        id: "cm00rz3mb0009fasajrd23xah",
        title: "Fullstack Developer",
        slug: "corp-fullstack-developer",
        description: "",
        company: "Corp",
        location: "Worldwide",
        permanency: "INTERNSHIP",
        featured: false,
        tags: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-19T09:09:57.395Z",
      },
      {
        id: "cm00s0pb5000afasa013inrt8",
        title: "Software Engineer",
        slug: "partners-enterprises-software-engineer",
        description: "",
        company: "Partners Enterprises",
        location: "UK",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Fullstack", "Midweight", "JavaScript", "Django", "Python"],
        imgUrl: "",
        createdAt: "2024-08-19T09:11:12.161Z",
      },
      {
        id: "cm00s5bf4000dfasarcofal1z",
        title: "Software Engineer",
        slug: "enterprises-systems-software-engineer",
        description: "",
        company: "Enterprises Systems",
        location: "Worldwide",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Fullstack", "Midweight", "Python", "React"],
        imgUrl: "",
        createdAt: "2024-08-19T09:14:47.440Z",
      },
      {
        id: "cm00s7bk8000efasa1rvk6lwj",
        title: "Junior Developer",
        slug: "innovations-corp-corp-junior-developer",
        description: "",
        company: "Innovations Corp Corp",
        location: "Worldwide",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Backend", "Junior", "Ruby", "RoR"],
        imgUrl: "",
        createdAt: "2024-08-19T09:16:20.936Z",
      },
      {
        id: "cm00s8t69000ffasayvgsodkz",
        title: "Front-end Dev",
        slug: "group-tech-corp-front-end-dev",
        description: "",
        company: "Group Tech Corp",
        location: "UK",
        permanency: "FULL_TIME",
        featured: true,
        tags: ["Fullstack", "Midweight", "JavaScript", "Django", "Python"],
        imgUrl: "",
        createdAt: "2024-08-19T09:17:30.417Z",
      },
      {
        id: "cm00sabjq000gfasavx08gqbw",
        title: "Junior Frontend Developer",
        slug: "tech-junior-frontend-developer",
        description: "",
        company: "Tech",
        location: "USA",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Fullstack", "Midweight", "JavaScript", "Sass", "Ruby"],
        imgUrl: "",
        createdAt: "2024-08-19T09:18:40.886Z",
      },
      {
        id: "cm00s27lj000bfasacbowu8e4",
        title: "Fullstack Developer",
        slug: "industries-partners-group-fullstack-developer",
        description: "",
        company: "Industries Partners Group",
        location: "Worldwide",
        permanency: "FULL_TIME",
        featured: false,
        tags: ["Fullstack", "Midweight", "JavaScript", "Django", "Python"],
        imgUrl: "",
        createdAt: "2024-08-19T09:12:22.519Z",
      },
      {
        id: "cm00scoo8000hfasafic00gnw",
        title: "Junior Developer",
        slug: "enterprises-systems-junior-developer",
        description: "",
        company: "Enterprises Systems",
        location: "Worldwide",
        permanency: "CONTRACT",
        featured: false,
        tags: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-19T09:20:31.209Z",
      },
      {
        id: "cm00se4dc000ifasajfyyddsb",
        title: "Junior Backend Developer",
        slug: "enterprises-consulting-junior-backend-developer",
        description: "",
        company: "Enterprises Consulting",
        location: "USA",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "React", "Sass", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-19T09:21:38.209Z",
      },
      {
        id: "cm00sfqw3000jfasaq5i0xyjj",
        title: "Fullstack Developer",
        slug: "enterprises-corp-fullstack-developer",
        description: "",
        company: "Enterprises Corp",
        location: "Remote",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-19T09:22:54.051Z",
      },
      {
        id: "cm00sji0b000kfasadmstdeu2",
        title: "Junior Frontend Developer",
        slug: "enterprises-technologies-junior-frontend-developer",
        description: "",
        company: "Enterprises Technologies",
        location: "USA",
        permanency: "INTERNSHIP",
        featured: false,
        tags: ["Fullstack", "Midweight", "JavaScript", "Sass", "Ruby"],
        imgUrl: "",
        createdAt: "2024-08-19T09:25:49.164Z",
      },
      {
        id: "cm00skmbs000lfasaibbeyptp",
        title: "Junior Backend Developer",
        slug: "global-junior-backend-developer",
        description: "",
        company: "Global",
        location: "Worldwide",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "React", "Sass", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-19T09:26:41.416Z",
      },
      {
        id: "cm00small000mfasap1v8p9lv",
        title: "Junior Frontend Developer",
        slug: "corp-consulting-junior-frontend-developer",
        description: "",
        company: "Corp Consulting",
        location: "Worldwide",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "React", "Sass", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-19T09:27:59.529Z",
      },
      {
        id: "cm00snd0a000nfasanfs8vy36",
        title: "Fullstack Developer",
        slug: "industries-systems-industries-fullstack-developer",
        description: "",
        company: "Industries Systems Industries",
        location: "USA",
        permanency: "PART_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "Vue", "JavaScript", "Sass"],
        imgUrl: "",
        createdAt: "2024-08-19T09:28:49.306Z",
      },
      {
        id: "cm00sozug000ofasa1e1vxsb2",
        title: "Junior Frontend Developer",
        slug: "group-junior-frontend-developer",
        description: "",
        company: "Group",
        location: "Worldwide",
        permanency: "FULL_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "CSS", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-19T09:30:05.560Z",
      },
      {
        id: "cm00sqkmp000pfasa8aholdjj",
        title: "Senior Frontend Developer",
        slug: "group-group-senior-frontend-developer",
        description: "",
        company: "Group Group",
        location: "USA",
        permanency: "FULL_TIME",
        featured: false,
        tags: ["Frontend", "Junior", "HTML", "Sass", "JavaScript"],
        imgUrl: "",
        createdAt: "2024-08-19T09:31:19.154Z",
      },
    ],
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
